import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#25292e', padding: 20 },
  homeContainer: { flex: 1, backgroundColor: '#25292e', justifyContent: 'center', padding: 40 },
  title: { color: '#fff', fontSize: 28, fontWeight: 'bold', textAlign: 'center', marginTop: 20 },
  label: { color: '#fff', marginTop: 10, fontWeight: '600' },
  chartLabel: { color: '#fff', fontSize: 18, fontWeight: 'bold', textAlign: 'center', marginTop: 20 },
  input: { borderWidth: 1, borderColor: '#555', color: '#fff', padding: 12, borderRadius: 8, marginTop: 5 },
  pickerWrapper: { backgroundColor: '#555', borderRadius: 20, marginVertical: 10, height: 55, justifyContent: 'center', overflow: 'hidden' },
  picker: { width: '100%' },
  pickerItem: { fontSize: 16, height: 40, color: '#000' },
  bookItem: { borderBottomWidth: 1, borderBottomColor: '#333', paddingVertical: 10 },
  bookTitle: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  bookSub: { color: '#bbb', fontSize: 13 },
  chartsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 15 },
  chartBox: { width: '48%', alignItems: 'center' },
  smallLabel: { color: '#fff', fontSize: 14, marginBottom: 5, fontWeight: 'bold' },
  bookItemRow: {
    flexDirection: 'row',     
    alignItems: 'center',      
    borderBottomWidth: 1,
    borderBottomColor: '#333',
    paddingVertical: 10,
  },
  deleteButton: {
    width: 40,             
    height: 40,               
  },
  deleteButtonText: {
    color: '#b72b2b',         
    fontSize: 18,        
    fontWeight: 'bold',    
  },

  badge: {
    backgroundColor: '#8e41e5',
    paddingHorizontal: 5,    
    paddingVertical: 0,
    borderRadius: 4,         
    marginLeft: 8,           
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',         
  },
  badgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    lineHeight: 14,          
  },
  backButtonFloating: {
    position: 'absolute',
    top: 58,                
    left: 20,
    zIndex: 5,            
    backgroundColor: 'rgba(0, 0, 0, 0.5)', 
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: '#444',
  },
    suggestionsContainer: {
    backgroundColor: '#333',    
    borderRadius: 12,            
    marginTop: 5,                
    position: 'absolute',        
    top: 75,                     
    left: 0,
    right: 0,
    zIndex: 999,                 
    elevation: 10,               
    shadowColor: '#000',         
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    borderWidth: 1,
    borderColor: '#444',        
    overflow: 'hidden',          
  },
  suggestionItem: {
    paddingVertical: 14,        
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#444',
    flexDirection: 'row',        
    alignItems: 'center',
  },
  suggestionText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
  },

  chartBox: {
    backgroundColor: '#2c3139',
    borderRadius: 16,
    paddingVertical: 15,
    paddingHorizontal: 10,
    minHeight: 200, 
    elevation: 4,   
    shadowColor: '#000', 
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  smallLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 10, 
    textAlign: 'center',
    width: '100%',
  },


});

